theme: minima
title: Sagar Maurya 
description: Ready to learn and Eveready to earn
url: "https://tnac.net"
# personal links

email: hello@sagarmaurya.dev
github_username:  sagarising
facebook_username: stormym3
instagram_username: stormym3
linkedin_username: sagar-maurya-41b9a4112